Fix: Comando2

diff --git a/.github/workflows/test-pipeline.yml b/.github/workflows/test-pipeline.yml
--- a/.github/workflows/test-pipeline.yml
+++ b/.github/workflows/test-pipeline.yml
@@ -29,11 +29,19 @@ jobs:
     # Usamos -f para indicar la ruta exacta del archivo
     - name: Levantar Docker
       run: |
-        # Buscamos el archivo y lo guardamos en una variable
-        COMPOSE_FILE=$(find . -name "docker-compose.yml" | head -n 1)
-        echo "Archivo encontrado en: $COMPOSE_FILE"
-        docker compose -f $COMPOSE_FILE up -d
+        echo "Lista de archivos en el repositorio:"
+        find . -name "*.yml" -o -name "*.yaml"
         
+        COMPOSE_FILE=$(find . -name "docker-compose.yml" | head -n 1)
+        
+        if [ -z "$COMPOSE_FILE" ]; then
+          echo "ERROR CRÍTICO: No se encontró ningún archivo llamado docker-compose.yml"
+          exit 1
+        fi
+        
+        echo "Archivo encontrado en: $COMPOSE_FILE"
+        docker compose -f "$COMPOSE_FILE" up -d
+
     - name: Esperar servicios
       run: sleep 30 # Tiempo para que Kafka y la App arranquen
 
